name: demo

type: php:5.6

disk: 2048

relationships:
    database: "mysql:mysql"

dependencies:
    php:
        "drush/drush": "7.0.0"

web:
    document_root: "/"
    passthru: "/index.php"

build:
  flavor: drupal

mounts:
    "/public/sites/default/files": "shared:files/files"
    "/tmp": "shared:files/tmp"
    "/config": "shared:files/config"
    "/private": "shared:files/private"
    "/drush-backups": "shared:files/drush-backups"

crons:
    drupal:
        spec: "0 */2 * * *"
        cmd: "cd public ; drush core-cron"

hooks:
  deploy: "cd public ; drush updb -y"
