"https://{default}/":
    type: upstream
    upstream: "demo:php"

"http://{default}/":
    type: redirect
    to: "https://{default}/"

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"

"http://www.{default}/":
    type: redirect
    to: "http://{default}/"
